AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HyP3URL:
    Type: String

  QueueName:
    Type: String

  MattermostPAT:
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Lambda}"

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sqs:GetQueueAttributes
                Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueName}"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          MATTERMOST_PAT: !Ref MattermostPAT
      Code: src/
      Handler: status_messages.lambda_handler
      Role: !GetAtt Role.Arn
      Runtime: python3.12
      Timeout: 10

  Schedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "cron(0 13 ? * 2 *)"
      Targets:
        - Arn: !GetAtt Lambda.Arn
          Id: lambda

  EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Lambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Schedule.Arn
