name: Weekly ITSLIVE Dead Letter Queue

on:
  schedule:
    # Run @ 5:00 AM ( 2:00 PM UTC) every Monday
    - cron: '0 14 * * 1'

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.V2_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.V2_AWS_SECRET_ACCESS_KEY }}
  MATTERMOST_PAT: ${{ secrets.MATTERMOST_PAT }}

jobs:
  mm-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Install
        shell: bash -l {0}
        run: |
          python -m pip install .

      - name: Generate ITSLIVE report
        env:
          MATTERMOST_ITSLIVE_CHANNEL: ${{ github.event.inputs.mattermost_itslive_channel }}
        shell: bash -l {0}
        run: python mattermost-update.py ${MATTERMOST_ITSLIVE_CHANNEL}